---
- name: Reload systemd
  become: yes
  command: systemctl daemon-reload
  notify:
    - Stop flannel
    - Remove flannel's local subnet config file
    - Start flannel
    - Reconfigure docker

- name: Stop flannel
  become: yes
  service: name={{flanneld_service}} state=stopped

- name: Remove flannel's local subnet config file
  become: yes
  file: path=/run/flannel/ state=absent
  when: remove_local_subnet_config

- name: Start flannel
  become: yes
  service: name={{flanneld_service}} state=started enabled=yes

- name: Reconfigure docker
  command: /bin/true
  notify:
    - Stop docker
    - Destroy docker0
    - Start docker

- name: Stop docker
  become: yes
  service: name=docker.service state=stopped

- name: Destroy docker0
  become: yes
  shell: >
    ip link set docker0 down &&
    brctl delbr docker0 ||
    true

- name: Start docker
  become: yes
  service: name=docker.service state=started
